# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  app:
    image: maven:3-jdk-8-alpine
    env_file:
      - .env
      - ./data-collectors/$COLLECTOR/.env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    volumes:
      - ./data-collectors/$COLLECTOR/:/code
      - ~/.m2/:/var/maven/.m2
    working_dir: /code
    command: mvn -Duser.home=/var/maven -U clean tomcat:run
