version: "3.4"

services:
  app:
    image: maven:3-eclipse-temurin-11-alpine
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000
    entrypoint: >
      mvn
        -Duser.home=/var/maven
        -Djetty.http.port=9001
        clean
        compile
        test
        jetty:run
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/.m2/:/var/maven/.m2:Z
      - ./:/code
    working_dir: /code
    tty: true
