version: "3.4"

services:
  app:
    image: maven:3-jdk-8-alpine
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    command: sh -c "mvn -Duser.home=/var/maven -DskipTests clean package spring-boot:repackage &&  java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9000 -jar target/ROOT.jar"
    volumes:
      - ~/.m2/:/var/maven/.m2
      - ./:/code
    ports:
      - 9000:9000
      - 9001:9001
    working_dir: /code
    tty: true
