# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      dockerfile_inline: |
        FROM golang:1.21.5-alpine
        WORKDIR /code
        RUN go install github.com/go-delve/delve/cmd/dlv@latest
    env_file:
      - .env
    entrypoint: >
      dlv --listen=:4000 --accept-multiclient --continue --headless=true --api-version 2 debug main.go
    ports:
      - 4000:4000
    volumes:
      - ./src:/code
      - ~/.go/pkg/mod:/go/pkg/mod
    working_dir: /code