name: CI/CD parking-offstreet-sta

on:
  push:
    paths:
      - "data-collectors/parking-offstreet-sta/**"
      - ".github/workflows/ci-parking-offstreet-sta.yml"

env:
  WORKING_DIRECTORY: data-collectors/parking-offstreet-sta
  PROJECT_NAME: odh-mobility-dc-parking-offstreet-sta
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
  DOCKER_TAG: ${{ github.sha }}
  GO_VERSION: ^1.21.4

jobs:
  deploy-test:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-test
    env:
      KEYCLOAK_URL: https://auth.opendatahub.testingmachine.eu
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}

          X_API_OAUTH_TOKEN_URI: ${{ secrets.PARKING_STA_API_OAUTH_TOKEN_URI }}
          X_API_OAUTH_USERNAME: ${{ secrets.PARKING_STA_API_OAUTH_USERNAME }}
          X_API_OAUTH_PASSWORD: ${{ secrets.PARKING_STA_API_OAUTH_PASSWORD }}
          X_API_OAUTH_CLIENT_SECRET: ${{ secrets.PARKING_STA_API_OAUTH_CLIENT_SECRET }}
          X_API_OAUTH_CLIENT_ID: ${{ secrets.PARKING_STA_API_OAUTH_CLIENT_ID }}

          X_ORIGIN: skidata

          X_BASE_URI: ${{ env.KEYCLOAK_URL }}/json
          X_OAUTH_AUTH_URI: ${{ env.KEYCLOAK_URL }}/auth
          X_OAUTH_TOKEN_URI: ${{ env.KEYCLOAK_URL }}/auth/realms/noi/protocol/openid-connect/token
          X_OAUTH_CLIENT_ID: odh-mobility-datacollector
          X_OAUTH_CLIENT_NAME: odh-mobility-datacollector
          X_OAUTH_CLIENT_SECRET: ${{ secrets.DATACOLLECTORS_CLIENT_SECRET_TEST }}
          X_OAUTH_CLIENT_SCOPE: openid
          
          X_PROVENANCE_VERSION: ${{ github.sha }}
          X_PROVENANCE_NAME: odh-mobility-dc-parking-offstreet-sta
          
          X_LOG_LEVEL: INFO

          X_SCHEDULER_CRON: "0 */5 * * * *"
          

      - name: Build go application
        run: go build -o main
        working-directory: ${{ env.WORKING_DIRECTORY }}/src

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure/ansible
          hosts: 'test'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}

  deploy-prod:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/prod'
    concurrency: deploy-prod
    env:
      KEYCLOAK_URL: https://auth.opendatahub.com
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}

          X_API_OAUTH_TOKEN_URI: ${{ secrets.PARKING_STA_API_OAUTH_TOKEN_URI }}
          X_API_OAUTH_USERNAME: ${{ secrets.PARKING_STA_API_OAUTH_USERNAME }}
          X_API_OAUTH_PASSWORD: ${{ secrets.PARKING_STA_API_OAUTH_PASSWORD }}
          X_API_OAUTH_CLIENT_SECRET: ${{ secrets.PARKING_STA_API_OAUTH_CLIENT_SECRET }}
          X_API_OAUTH_CLIENT_ID: ${{ secrets.PARKING_STA_API_OAUTH_CLIENT_ID }}

          X_ORIGIN: skidata

          X_BASE_URI: https://mobility.share.opendatahub.com/json
          X_OAUTH_AUTH_URI: ${{ env.KEYCLOAK_URL }}/auth
          X_OAUTH_TOKEN_URI: ${{ env.KEYCLOAK_URL }}/auth/realms/noi/protocol/openid-connect/token
          X_OAUTH_CLIENT_ID: odh-mobility-datacollector
          X_OAUTH_CLIENT_NAME: odh-mobility-datacollector
          X_OAUTH_CLIENT_SECRET: ${{ secrets.DATACOLLECTORS_CLIENT_SECRET_PROD }}
          X_OAUTH_CLIENT_SCOPE: openid
          
          X_PROVENANCE_VERSION: ${{ github.sha }}
          X_PROVENANCE_NAME: odh-mobility-dc-parking-offstreet-sta
          
          X_LOG_LEVEL: INFO

          X_SCHEDULER_CRON: "0 */5 * * * *"
          

      - name: Build go application
        run: go build -o main
        working-directory: ${{ env.WORKING_DIRECTORY }}/src

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure/ansible
          hosts: 'prod'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}
          